# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMtkr06ZMli31u1-bzdltQAU4Y9bm705
"""

!pip install streamlit

# 🎨 Step 2: Build the Web UI (Streamlit)
# ✅ Create dashboard.py
import streamlit as st
import pandas as pd

from newsbot_backend import train_model, analyze_article

# Load dataset (you already created)
df = pd.read_csv("news_dataset.csv")

# Train model once
model, vectorizer = train_model(df)

# -------------------------------
# UI
# -------------------------------
st.set_page_config(page_title="NewsBot 2.0", layout="wide")

st.title("📰 NewsBot Intelligence System 2.0")
st.markdown("AI-powered News Analysis Dashboard")

# Input
user_input = st.text_area("✍️ Enter a news article:")

if st.button("Analyze Article"):

    if user_input.strip() == "":
        st.warning("Please enter some text.")
    else:
        result = analyze_article(user_input, model, vectorizer)

        st.success("Analysis Complete!")

        col1, col2 = st.columns(2)

        # CATEGORY
        with col1:
            st.subheader("🏷️ Category")
            st.write(result["category"])

        # SENTIMENT
        with col2:
            st.subheader("😊 Sentiment")
            st.write(result["sentiment"])

        # ENTITIES
        st.subheader("🔍 Named Entities")
        if result["entities"]:
            for ent, label in result["entities"]:
                st.write(f"{ent} ({label})")
        else:
            st.write("No entities found.")

        # PROCESSED TEXT
        st.subheader("🧹 Processed Text")
        st.write(result["processed"])

# Install necessary libraries for the backend
!pip install -qqq nltk scikit-learn spacy
!python -m spacy download en_core_web_sm -qqq

import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import spacy

nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('omw-1.4', quiet=True)

# Load spaCy model
try:
    nlp = spacy.load('en_core_web_sm')
except OSError:
    print("Downloading spaCy model 'en_core_web_sm'...")
    spacy.cli.download("en_core_web_sm")
    nlp = spacy.load('en_core_web_sm')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()
    text = re.sub(f'[{re.escape(string.punctuation)}]', '', text)
    words = text.split()
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]
    return ' '.join(words)

def train_model(df):
    # For demonstration, we'll create dummy sentiment labels based on content length.
    # In a real scenario, you'd have actual labeled data for sentiment.
    # For category, we'll use the 'target' column as the category.

    df['processed_content'] = df['content'].apply(preprocess_text)

    # Dummy sentiment: assign 'positive' if content is long, 'negative' if short
    # This is a simplification; real sentiment analysis requires training on sentiment-labeled data.
    df['sentiment_label'] = df['content'].apply(lambda x: 'positive' if len(x) > 500 else 'negative')

    vectorizer = TfidfVectorizer(max_features=5000)
    X = vectorizer.fit_transform(df['processed_content'])

    # Train category model
    category_model = LogisticRegression(max_iter=1000, random_state=42)
    category_model.fit(X, df['target'])

    # Train sentiment model (using dummy sentiment for now)
    sentiment_model = LogisticRegression(max_iter=1000, random_state=42)
    sentiment_model.fit(X, df['sentiment_label'])

    # Return a dictionary of models, so analyze_article can access both
    return {'category_model': category_model, 'sentiment_model': sentiment_model}, vectorizer

def analyze_article(article_text, models, vectorizer):
    processed_article = preprocess_text(article_text)
    article_vector = vectorizer.transform([processed_article])

    # Predict category
    category_prediction = models['category_model'].predict(article_vector)[0]
    # Map target numbers to names if possible, otherwise use the number
    # For now, let's just return the number, as we don't have the mapping here.
    category_name = f"Category {category_prediction}" # Placeholder

    # Predict sentiment
    sentiment_prediction = models['sentiment_model'].predict(article_vector)[0]

    # Named Entity Recognition
    doc = nlp(article_text)
    entities = [(ent.text, ent.label_) for ent in doc.ents]

    return {
        'category': category_name,
        'sentiment': sentiment_prediction,
        'entities': entities,
        'processed': processed_article
    }

import pandas as pd

# URL of dataset
url = "https://raw.githubusercontent.com/selva86/datasets/master/newsgroups.json"

# Load JSON data
df = pd.read_json(url)

# Save as CSV
df.to_csv("news_dataset.csv", index=False)

print("File saved as news_dataset.csv")

