# -*- coding: utf-8 -*-
"""news_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_av0nHzBKQq7vtZZXTCpaIqBDK3Zh8q
"""

import requests
from config import NEWS_API_KEY, BASE_UL

class NEWSAPIClient:
  def __init__(self):
    self.api_key = NEWS_API_KEY

  def fetch_top_headlines(self, query):
    # Fix: Corrected 'pamams' to 'params' and fixed typo in 'apiKey' assignment.
    params = {
      'apiKey': self.api_key,
      'q': query,
      "language": "en",
      "pagesize": 10
    }
    # Fix: Added 'params' to requests.get call and removed duplicate 'BASE_UL' import.
    # Also, 'BASE_UL' should likely be 'BASE_URL'. Assuming it is a typo.
    response = requests.get(BASE_UL, params=params)

    if response.status_code == 200:
      # Fix: Corrected 'rasise' to 'raise' and 'response.status.code' to 'response.status_code'
      return response.json()
    else:
      raise Exception(f"API Error: {response.status_code}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile config.py
# NEWS_API_KEY = "YOUR_NEWS_API_KEY"
# BASE_URL = "https://newsapi.org/v2/top-headlines" # Assuming this is the correct base URL
#

import requests
from config import NEWS_API_KEY, BASE_URL

class NEWSAPIClient:
  def __init__(self):
    self.api_key = NEWS_API_KEY

  def fetch_top_headlines(self, query):
    params = {
      'apiKey': self.api_key,
      'q': query,
      "language": "en",
      "pagesize": 10
    }
    response = requests.get(BASE_URL, params=params)

    if response.status_code == 200:
      return response.json()
    else:
      raise Exception(f"API Error: {response.status_code}")

news_client = NEWSAPIClient()