# -*- coding: utf-8 -*-
"""WebApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tb-i-iiRY9bBQiyKHvmpAIgOQfyMFvHh
"""

# Step 3: Run the Web App
!pip install streamlit
!streamlit run dashboard.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dashboard.py
# import streamlit as st
# import pandas as pd
# 
# st.set_page_config(layout="wide")
# st.title("Simple Streamlit Dashboard with DataFrame")
# st.write("Welcome to your updated Streamlit application in Colab!")
# 
# # Create a sample DataFrame
# data = {
#     'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
#     'Price': [1200, 25, 75, 300],
#     'Quantity': [10, 50, 30, 5]
# }
# sample_df = pd.DataFrame(data)
# 
# st.subheader("Sample Product Data")
# st.dataframe(sample_df)
# 
# st.write("You can modify this file and rerun the previous Streamlit command to see changes.")

"""Now that `dashboard.py` is updated, please run the following cell to restart your Streamlit app and see the DataFrame:"""

!streamlit run dashboard.py

"""Now, let's update `dashboard.py` to include this DataFrame. After this, you will need to rerun the cell with `!streamlit run dashboard.py` to see the changes in your web app."""